version: "3.3"

services:
  blog-backend:
    build:
      context: .
      args:
        - DATABASE_HOST=$DATABASE_HOST
        - DATABASE_PORT=$DATABASE_PORT
    restart: always
    volumes:
      - $BLOG_RESOURCES:/app/public/uploads
    ports:
      - "127.0.0.1:7001:1337"
    networks:
      - blogdb

networks:
  blogdb:
    external: true
